//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campeonato.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO_JUGADOR
    {
        public int ID { get; set; }
        public int ID_JUGADOR { get; set; }
        public int ID_EQUIPO { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual JUGADOR JUGADOR { get; set; }
    }
}
