//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campeonato.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO_PARTIDO
    {
        public int ID_PARTIDO { get; set; }
        public int ID_EQUIPO_CASA { get; set; }
        public int ID_EQUIPO_VISITA { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual EQUIPO EQUIPO1 { get; set; }
        public virtual PARTIDO PARTIDO { get; set; }
    }
}
