//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campeonato.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO
    {
        public EQUIPO()
        {
            this.EQUIPO_JUGADOR = new HashSet<EQUIPO_JUGADOR>();
            this.EQUIPO_PARTIDO = new HashSet<EQUIPO_PARTIDO>();
            this.EQUIPO_PARTIDO1 = new HashSet<EQUIPO_PARTIDO>();
            this.EQUIPO_TORNEO = new HashSet<EQUIPO_TORNEO>();
        }
    
        public int ID { get; set; }
        public string NOMBRE_EQUIPO { get; set; }
        public System.DateTime FECHA_FUNDACION { get; set; }
        public int ID_PROVINCIA { get; set; }
        public int ID_CANTON { get; set; }
        public int ID_DISTRITO { get; set; }
    
        public virtual ICollection<EQUIPO_JUGADOR> EQUIPO_JUGADOR { get; set; }
        public virtual ICollection<EQUIPO_PARTIDO> EQUIPO_PARTIDO { get; set; }
        public virtual ICollection<EQUIPO_PARTIDO> EQUIPO_PARTIDO1 { get; set; }
        public virtual ICollection<EQUIPO_TORNEO> EQUIPO_TORNEO { get; set; }
        public virtual Canton Canton { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
