//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campeonato.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOLES
    {
        public int GOLES1 { get; set; }
        public int ID_MARCADOR { get; set; }
        public int ID_JUGADOR { get; set; }
        public int ID_TORNEO { get; set; }
    
        public virtual TORNEO TORNEO { get; set; }
    }
}
