//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campeonato.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIDO
    {
        public PARTIDO()
        {
            this.EQUIPO_PARTIDO = new HashSet<EQUIPO_PARTIDO>();
        }
    
        public int ID { get; set; }
        public System.DateTime FECHA_PARTIDO { get; set; }
        public int GOL_EQUIPO_CASA { get; set; }
        public int GOL_EQUIPO_VISITA { get; set; }
        public int ID_TORNEO { get; set; }
    
        public virtual ICollection<EQUIPO_PARTIDO> EQUIPO_PARTIDO { get; set; }
        public virtual TORNEO TORNEO { get; set; }
    }
}
