//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campeonato.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public Provincia()
        {
            this.Canton = new HashSet<Canton>();
            this.EQUIPO = new HashSet<EQUIPO>();
            this.JUGADOR = new HashSet<JUGADOR>();
        }
    
        public int id_Provincia { get; set; }
        public string nombreProvincia { get; set; }
        public string usuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCrea { get; set; }
        public string usuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
        public string vc_Estado { get; set; }
    
        public virtual ICollection<Canton> Canton { get; set; }
        public virtual ICollection<EQUIPO> EQUIPO { get; set; }
        public virtual ICollection<JUGADOR> JUGADOR { get; set; }
    }
}
