//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campeonato.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TORNEO
    {
        public TORNEO()
        {
            this.EQUIPO_TORNEO = new HashSet<EQUIPO_TORNEO>();
            this.GOLES = new HashSet<GOLES>();
            this.PARTIDO = new HashSet<PARTIDO>();
        }
    
        public int ID { get; set; }
        public int NOMBRE_TORNETO { get; set; }
        public System.DateTime FECHA_INI { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public Nullable<int> CANTIDAD_EQUIPOS { get; set; }
        public string DEDICATORIA { get; set; }
    
        public virtual ICollection<EQUIPO_TORNEO> EQUIPO_TORNEO { get; set; }
        public virtual ICollection<GOLES> GOLES { get; set; }
        public virtual ICollection<PARTIDO> PARTIDO { get; set; }
    }
}
