//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campeonato.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string NOMBRE_USUARIO { get; set; }
        public string TIPO_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO1 { get; set; }
        public System.DateTime ULT_FECHA_INGRESO { get; set; }
    }
}
